### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-debux#14]
* Increment indent on subforms (bearing in mind that ->> is made of subforms)

**Comment by mike-thompson-day8** [comment]
I'm not sure what this issue means.  Indentation currently happens.  

Just in case this comment is specific to `->>`, I've run an experiment with it and looked at indentation and I see this. 
![image](https://user-images.githubusercontent.com/3033376/83266311-007e4480-a206-11ea-9129-bb625a8a2b39.png)

Seems to me like enough indentation is happening.  If anything there's an argument for less indent. 

Confused. Closing.

**Comment by danielcompton** [comment]
I’m confused too! Good to close.
