### ISSUE TITLE
index.html is interfering with figwheel-main

### ISSUE THREAD

**Issue by antonmos** [Day8/re-frame-debux#28]
Per https://figwheel.org/docs/ring-handler.html#the-last-handler, figwheel.main will serve index.html from classpath ahead of using the provided ring handler.

This makes it impossible to both use figwheel-main, having it serve the app routes and use re-frame/tracing.

Thanks in advance!

**Comment by antonmos** [comment]
Thank you for fixing this so quickly! When can I expect a release?

**Comment by antonmos** [comment]
Any word on a release?
Thanks!

**Comment by danielcompton** [comment]
I no longer have any access to deploy releases to Clojars, @superstructor might be available at some point.

**Comment by mike-thompson-day8** [comment]
@antonmos we're just chasing down a mysterious issue with shadow-clj and re-frame-10x.  Waiting on that for a release.

**Comment by superstructor** [comment]
Sorry for the delay @antonmos and thanks for the fix @danielcompton. `0.5.2` has been released.

**Comment by antonmos** [comment]
Thank you!!!
