### ISSUE TITLE
June 2020 Sprint

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-debux#32]
We're going to spend some time improving the tracing.

Tracing is currently still a little toy and not suited to use with re-frame because it can't walk data literals like vectors and maps.

Eventually, everything that happens when an event is handled will be traced. That means the interceptors, the event handler, the subscription handlers and the view renders. Everything. Within re-frame-10x, the existing `Event` tab will likely disappear and a re-written `Trace` tab will show all trace, one function after another.  To facilitate this, we will ultimately adjust the various re-frame `reg-*` functions to become macros and automatically turn `fn` handlers into `fn-traced` ones.  
We want you, the programmer, to be able to browse and inspect all this trace in `re-frame-10x` and have a REPL (in the browser) to interact with this data.  

So, that's the context.  Now, here's the specific todos: 
  - [x] all the tested are currently commented out.  Figure out why.  Establish a testing regime to underpin ongoing work.
  - [x] https://github.com/day8/re-frame-debux/issues/15 https://github.com/day8/re-frame-debux/issues/23 https://github.com/day8/re-frame-debux/issues/29 https://github.com/day8/re-frame-debux/issues/31 determine the set of macros not currently covered or covered incorrectly.  Create a plan to get full coverage. Check to see if downstream debux has useful changes and merge them. 
  - [x]  https://github.com/day8/re-frame-debux/issues/1 figure out how to trace into a map literal.  At the moment, the tracing just stops at a map literals. This is especially important  when tracing event handlers which return a map literal 
       `{:db  (update db assoc :a  (inc 5)  :b (if true :t :f))}` 
  - [x] figure out how to trace into vectors - this is needed so we can trace views. So this todo is really ... be able to trace into hiccup creation where the vectors might contain nested code, eg:
        `[:div  {:style {:color (if true (str "hello " "world") :never}}  (if true [inc "putting inc symbol inside a vector"])]`
  - [x] preserve metadata especially on vectors in event handlers
  - [x] debux has some way by which the processing of "other" macros can be "registered" - use that?  
  - [ ] what to do about exceptions?
  - [ ] review what trace is sent to re-frame-10x. When we are tracing one function after another, are we given enough trace to know when a new function starts, and what it is, etc.  i suspect the answer is yes, but we need to check. 

Integrate with Abra:
  - [x] ~~allow different consumers to register to receive traces  (at the moment re-frame-10x is the only consumer, so the job here is to allow other parties - like abra - to register to get the trace)~~ This seems to be a feature of re-frame trace
  - [x] ~~adjust macros to be compatible with self-hosted ClojureScript (talk to Isaac). Probably means switching to use https://github.com/cgrand/macrovich?~~

**Comment by stumitchell** [comment]
Allow you to register your own trace for your own macros

**Comment by mike-thompson-day8** [comment]
When the following form gets evaluated: `(inc 1)` it is done in three steps (because it is a list, and lists evaluate to a function call):
  1. Every element of the list is evaluated ... that means `inc` gets evaluated and `1` gets evaluated. `inc` is a symbol and it will evaluate to what it is bound to ... which is a function. and `1` will evaluate to `1`
  2. A function that `inc` evaluated to is called with `1` as the actual parameter
  3. The return value of the function is what the form evaluates to

Now .. we aren't showing all of this trace currently. We specifically skip the evaluation of `inc` and `1` because it isn't interesting.  And that's a good thing.  Otherwise, the evaluation trace will be too noisy.  And anyway, how would we even indicate that `inc` is a function?  

So ... our current approach is very understandable even if it is inaccurate by omission.  

However ... and this is the real point I'm trying to make ... there might be cases (when teaching ClojureScript) where we would want to show ALL the trace, not the simplified version. So we might want to be able to configure the generation of trace to include or exclude the noisy bits.  OR produce all the trace all the time, but tag some of it as "noisy" so it can, optionally, be filtered out of what is show to the users.

**Comment by stumitchell** [comment]
`adjust macros to be compatible with self-hosted ClojureScript (talk to Isaac). Probably means switching to use https://github.com/cgrand/macrovich?`

This was harder than we thought, for instance `macroexpand` in cljs doesn't work very well (it is a macro not a function) 
https://github.com/anmonteiro/lumo/issues/501

However, we now know that we should be able to use a bootstrap build to use clj macros

**Comment by stumitchell** [comment]
<s>1. Format top section code across multiple lines for easier readability
    The code shown in the top section needs to be formatted across multiple lines. DJ had a large function which word wrapped over half a dozen lines and it was very confusing:
`(let [deserialised (-> (get content "data") (cljs-reader/read-string) (update :mwi (fn [m] (let [bytes (-> (string/split (:gzip m) #"\,") clj->js js/Uint8Array.from)] (assoc m :xml-str (utils/ungzip bytes {:to "string"})))))) scion-brief (get deserialised :brief) mwi-name (get-in deserialised [:mwi :name]) xml-str (get-in deserialised [:mwi :xml-str]) load-flow-defaults (assoc flow-defaults :show-progress? true)] (js/console.log "loaded job:" deserialised) {:db (-> db (assoc :progress {:description "DEV: loading exported curves job...", :complete? false, :event :day8.curves.steps.curves-header.support/load-job-file}) (load-brief scion-brief)), :dispatch [:day8.curves.steps.curves-header.support/load-contents mwi-name load-flow-defaults xml-str]})`
We concluded that rather than try to run the code through some formatter, we use the code from the original source as it represents the developer's mental model.  </s>

<s>
  2. Include the fn wrapper in the top section code
    Also as you can see, the above code starts from the let block. It would be more useful to see the full function so that we can see the args feeding into the let. In this case, that would look like the following (although some will be more complex):
`(fn-traced [{:keys [db]} [_ content]]] ...`
</s>

<s>
3. Reorder the forms in the bottom section for easier readability
    Although we understand that the order the forms appear in the bottom section is (mostly) in the order that they would be evaluated, (in most cases) this is the reverse order of the actual flow of the code. One exception is threading macros (possibly there are more), which do come out in the order as per the source code. This makes it more difficult to read and if we were able to organise the forms in a more linear order (with respect to the original code) that would be much easier to grok.
    To put it another way, we have some code going top to bottom (threaded code) and in between that we have it going bottom to top, so it is really quite a challenge to make sense of.
</s>

  4. Add a "code-folding" type feature to the bottom section
    We thought that when there are many forms (especially when there are loops), with lots of indentation in the bottom section, it would be helpful to have a folding feature so we can remove visual clutter as required.

  5. Hovering over a bottom form highlights the correct form at the top
     In other words, use a more sophisticated technique than regex searches. Stu seemed to think this would be possible by marking up the original code somehow.

  6. Rendering speed issues for complex functions
     When we were working in DJ's function above, it was taking 5 or more seconds to open and close simple forms. My theory on this is the "hover and see the result" feature requires rendering ALL forms as strings, truncating them, placing them in the DOM and then simply showing/hiding the result on hover (that part does work instantly though).
If that turns out to be the case, then perhaps showing results on hover is a toggle-able feature (either in settings or on the panel itself)

  7. "Vertical scrolling issues with app-db, subs and trace panels" (10x issue #262)
     This existing 10x issue really gets in the way some times so should be fixed ASAP.

**Comment by mike-thompson-day8** [comment]
Closing. We're finishing up this sprint.  

@stumitchell has made really solid progress over the last few weeks.  Attention now needs to swing back to `re-frame-10x` itself when we get some more time. 

Any issues not handled this time around have been broken out for next time.
