### ISSUE TITLE
`:ns-aliases` for shadow-cljs does not work

### ISSUE THREAD

**Issue by nimaai** [Day8/re-frame-debux#33]
Hi 

I am using:
```cljs
:release {:build-options
            {:ns-aliases
              {day8.re-frame.tracing day8.re-frame.tracing-stubs}}}
```
as instructed in the readme, but it does not work.

When making a shadow-cljs release I get an error: `The required namespace "day8.re-frame.tracing" is not available.` for a file where I use the tracing macros like `(:require [day8.re-frame.tracing :refer-macros [fn-traced]])`.

Any help would be appreciated.

P.S.:
- https://github.com/leihs/leihs-borrow/blob/9af214de1c91552822cfd4bd2286dbce61401b70/shadow-cljs.edn
- https://github.com/leihs/leihs-borrow/blob/9af214de1c91552822cfd4bd2286dbce61401b70/src/all/leihs/borrow/client/lib/localstorage.cljs

**Comment by superstructor** [comment]
I can see in the link to `shadow-cljs.edn` you provided it is depending on version `0.5.3` but support for `:ns-aliases` requires at least `0.5.5`.

Please try a later version and re-open or create a new issue if you still have an error.

Also to help other people from hitting this in future I have updated the README section on `:ns-aliases` to make the version requirement clear.
