### ISSUE TITLE
How do we handle repeated code traces?

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-debux#6]
* Mapping over a sequence
* Looping
* Reducing

**Comment by mike-thompson-day8** [comment]
I'm not clear there's an issue here. We just need to trace all these repeats. 

There may be an issue later when displaying them across in `re-frame-10x`, but that's not the concern of this tracing library.  If this happens then maybe that will require that extensive iteration is marked in some way.  Maybe.  Unknown.  

Closing.

**Comment by danielcompton** [comment]
Yep this was a presentation level issue, not collection.
